# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testAlamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testAlamofire
  pod 'Alamofire'

  target 'testAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
